### ISSUE TITLE
TypeError: scathach.milf is not a function

### ISSUE THREAD

**Issue by yorumi500** [sinkaroid/scathach-api#1]
```js
const client = require('scathach-api');
const scathach = new client();
 
scathach.milf().then(scathach => {console.log(scathach);});
```
`TypeError: scathach.milf is not a function`

**Desktop (please complete the following information):**
 - OS: Ubuntu server
 - Node version: 14.5

**Additional context**
how to fix it? sorry still learning about javasrcipt

**Comment by sinkaroid** [comment]
https://github.com/sinkaroid/scathach-api/blob/a19a4ed9abd1c77a552598e67c44364a77b570ea/typings/index.d.ts#L18
specific import is needed, either `porn`, `nsfw`, `real`, or `sex`
should something like this
```js
scathach.porn.milf().then(scathach => {console.log(scathach);});
```
